version: 2

jobs:
  build:
    working_directory: ~/app/
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: localstack/localstack:0.10.1.2

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Upgrade pipenv
          command: |
            pip install pipenv -U
      - run:
          name: install dependencies
          command: |
            pipenv sync --dev
      - run:
          name: prepare boto3 credentials and awscli
          command: |
            # install envsubst (provided by gettext-base)
            sudo apt install gettext-base

            # for deployment
            pip install awscli

            # prepare credentials
            mkdir -p ~/.aws
            cat ./infrastructure/aws/awscli/credentials.template | envsubst > ~/.aws/credentials
            cat ./infrastructure/aws/awscli/config.template | envsubst > ~/.aws/config
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "/home/circleci/.aws"
            - "/home/circlci/.local"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          name: run tests
          command: |
            make test

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - run:
          name: code checks (pylint, flake8, mypy)
          command: |
            make check


workflows:
  version: 2
  test-deploy:
    jobs:
      - build

