import os

BASIC_AUTH_USERNAME = os.getenv("BASIC_AUTH_USERNAME", None)
BASIC_AUTH_PASSWORD = os.getenv("BASIC_AUTH_PASSWORD", None)
BUCKET_NAME = os.getenv("BUCKET_NAME", None)
BUCKET_SITE_PREFIX = os.getenv("BUCKET_SITE_PREFIX", "")

AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION", "ap-northeast-1")

DEFAULT_BOTO3_S3_ENDPOINT = f"https://s3.{AWS_DEFAULT_REGION}.amazonaws.com"
DEFAULT_BOTO3_SQS_ENDPOINT = f"https://sqs.{AWS_DEFAULT_REGION}.amazonaws.com"
DEFAULT_BOTO3_SNS_ENDPOINT = f"https://sns.{AWS_DEFAULT_REGION}.amazonaws.com"
DEFAULT_BOTO3_EC2_ENDPOINT = f"https://ec2.{AWS_DEFAULT_REGION}.amazonaws.com"
DEFAULT_BOTO3_IAM_ENDPOINT = f"https://iam.{AWS_DEFAULT_REGION}.amazonaws.com"

BOTO3_ENDPOINTS = {
    "s3": os.getenv("BOTO3_S3_ENDPOINT", DEFAULT_BOTO3_S3_ENDPOINT),
    "sqs": os.getenv("BOTO3_SQS_ENDPOINT", DEFAULT_BOTO3_SQS_ENDPOINT),
    "sns": os.getenv("BOTO3_SNS_ENDPOINT", DEFAULT_BOTO3_SNS_ENDPOINT),
    "ec2": os.getenv("BOTO3_EC2_ENDPOINT", DEFAULT_BOTO3_EC2_ENDPOINT),
    "iam": os.getenv("BOTO3_IAM_ENDPOINT", DEFAULT_BOTO3_IAM_ENDPOINT),
}
